name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: "\\<*_&"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "🔐 Security"
    labels:
      - "security"
      - "dependencies"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🧪 Tests"
    labels:
      - "test"
      - "testing"
  - title: "Other Changes"
    label: "*"
version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "bug"
      - "fix"
      - "chore"
      - "maintenance"
      - "dependencies"
      - "security"
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
