# Noctis Minimus
kern.vt.color.0.rgb="#182a35"
kern.vt.color.1.rgb="#c08872"
kern.vt.color.2.rgb="#72c09f"
kern.vt.color.3.rgb="#c8a984"
kern.vt.color.4.rgb="#6196b8"
kern.vt.color.5.rgb="#c28097"
kern.vt.color.6.rgb="#72b7c0"
kern.vt.color.7.rgb="#c5cdd3"
kern.vt.color.8.rgb="#425866"
kern.vt.color.9.rgb="#ca8468"
kern.vt.color.10.rgb="#84c8ab"
kern.vt.color.11.rgb="#d1aa7b"
kern.vt.color.12.rgb="#68a4ca"
kern.vt.color.13.rgb="#c88da2"
kern.vt.color.14.rgb="#84c0c8"
kern.vt.color.15.rgb="#c5d1d3"
