# Noctis
[colors]
foreground = "#b2cacd"
background = "#052529"
cursor_bg = "#b2cacd"
cursor_border = "#b2cacd"
cursor_fg = "#052529"
selection_bg = "#0f3a3f"
selection_fg = "#b2cacd"

ansi = ["#324a4d","#e66533","#49e9a6","#e4b781","#49ace9","#df769b","#49d6e9","#b2cacd"]
brights = ["#47686c","#e97749","#60ebb1","#e69533","#60b6eb","#e798b3","#60dbeb","#c1d4d7"]
