# Noctis Lilac
[colors]
foreground = "#0c006b"
background = "#f2f1f8"
cursor_bg = "#0c006b"
cursor_border = "#0c006b"
cursor_fg = "#f2f1f8"
selection_bg = "#d5d3e5"
selection_fg = "#0c006b"

ansi = ["#0c006b","#e34e1c","#00b368","#f49725","#0094f0","#ff5792","#00bdd6","#8ca6a6"]
brights = ["#0f0080","#ff4000","#00d17a","#ff8c00","#0fa3ff","#ff6b9f","#00cbe6","#bbc3c4"]
