"""OIS architecture fabric contracts."""

from .fabrics import (
    AgentWorkspace,
    ComponentSpec,
    ContextRequest,
    EvaluationSpec,
    FabricKind,
    FabricSpec,
    InMemoryFabricRegistry,
    KnowledgeArtifact,
    LearningCandidate,
    LLMGatewaySpec,
    MiddlewareSpec,
    ModelRoute,
    MultimodalArtifact,
    ReasoningPattern,
    SocialSignal,
    StudioArtifact,
    VersionedRef,
    WorkerSpec,
    WorkflowSpec,
)

__all__ = [
    "AgentWorkspace",
    "ComponentSpec",
    "ContextRequest",
    "EvaluationSpec",
    "FabricKind",
    "FabricSpec",
    "InMemoryFabricRegistry",
    "KnowledgeArtifact",
    "LearningCandidate",
    "LLMGatewaySpec",
    "MiddlewareSpec",
    "ModelRoute",
    "MultimodalArtifact",
    "ReasoningPattern",
    "SocialSignal",
    "StudioArtifact",
    "VersionedRef",
    "WorkerSpec",
    "WorkflowSpec",
]
