"""Market-specific football probability models.

Each model prices a distinct statistical event family rather than forcing every
market through one generic match-result predictor. Inputs are deliberately
small and deterministic so fitted production estimators can replace the
reference distributions without changing the market contract.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Literal

from pydantic import BaseModel, Field

from .models import _poisson_pmf
from .schemas import MatchState


def _poisson_cdf(k: int, lam: float) -> float:
    return sum(_poisson_pmf(i, lam) for i in range(max(k, 0) + 1))


def _poisson_tail(k: int, lam: float) -> float:
    return max(0.0, min(1.0, 1.0 - _poisson_cdf(k - 1, lam)))


def _probability_event(count: float, line: float, over: bool) -> float:
    if line % 1 == 0.5:
        threshold = int(math.floor(line)) + 1
        return _poisson_tail(threshold, count) if over else _poisson_cdf(threshold - 1, count)
    threshold = int(line)
    if over:
        return _poisson_tail(threshold + 1, count)
    return _poisson_cdf(threshold, count)


class MarketProbability(BaseModel):
    """Canonical probability for one market selection."""

    model_id: str
    market: str
    selection: str
    probability: float = Field(ge=0, le=1)
    fair_odds: float = Field(gt=0)
    expected_value: float | None = None
    confidence: float = Field(ge=0, le=1, default=0.5)
    abstain: bool = False
    reason: str | None = None


class MarketPrediction(BaseModel):
    """Collection of selections generated by one market-specific model."""

    model_id: str
    market_family: str
    probabilities: list[MarketProbability]
    feature_snapshot: dict[str, float] = Field(default_factory=dict)


@dataclass(frozen=True)
class GoalMarketModel:
    model_id: str = "football.goal_market.v1"
    max_goals: int = 12

    def expected_goals(self, match: MatchState) -> tuple[float, float]:
        home = max(0.05, match.home.xg_for * match.home.attack_strength / max(match.away.defense_strength, 0.1))
        away = max(0.05, match.away.xg_for * match.away.attack_strength / max(match.home.defense_strength, 0.1))
        home *= 1.0 + match.home.home_advantage
        return home, away

    def predict(self, match: MatchState, lines: tuple[float, ...] = (1.5, 2.5, 3.5)) -> MarketPrediction:
        home, away = self.expected_goals(match)
        total = home + away
        probs: list[MarketProbability] = []
        for line in lines:
            over = _probability_event(total, line, True)
            for selection, p in ((f"over_{line}", over), (f"under_{line}", 1.0 - over)):
                probs.append(self._result("goals_ou", selection, p))
        btts = (1.0 - math.exp(-home)) * (1.0 - math.exp(-away))
        probs.extend([self._result("btts", "yes", btts), self._result("btts", "no", 1.0 - btts)])
        for side, lam in (("home", home), ("away", away)):
            for line in (0.5, 1.5, 2.5):
                over = _probability_event(lam, line, True)
                probs.extend([self._result(f"{side}_goals_ou", f"over_{line}", over), self._result(f"{side}_goals_ou", f"under_{line}", 1.0 - over)])
        return MarketPrediction(model_id=self.model_id, market_family="goals", probabilities=probs, feature_snapshot={"home_lambda": home, "away_lambda": away})

    def _result(self, market: str, selection: str, probability: float) -> MarketProbability:
        p = max(1e-9, min(1.0, probability))
        return MarketProbability(model_id=self.model_id, market=market, selection=selection, probability=p, fair_odds=1.0 / p)


@dataclass(frozen=True)
class ResultMarketModel(GoalMarketModel):
    model_id: str = "football.result_market.v1"

    def predict(self, match: MatchState) -> MarketPrediction:
        home_lam, away_lam = self.expected_goals(match)
        home = draw = away = 0.0
        for hg in range(self.max_goals + 1):
            for ag in range(self.max_goals + 1):
                p = _poisson_pmf(hg, home_lam) * _poisson_pmf(ag, away_lam)
                if hg > ag:
                    home += p
                elif hg == ag:
                    draw += p
                else:
                    away += p
        total = home + draw + away
        home, draw, away = home / total, draw / total, away / total
        probs = [self._result("1x2", "home", home), self._result("1x2", "draw", draw), self._result("1x2", "away", away)]
        probs += [self._result("double_chance", "1x", home + draw), self._result("double_chance", "12", home + away), self._result("double_chance", "x2", draw + away)]
        probs += [self._result("dnb", "home", home / max(home + away, 1e-9)), self._result("dnb", "away", away / max(home + away, 1e-9))]
        return MarketPrediction(model_id=self.model_id, market_family="result", probabilities=probs, feature_snapshot={"home_lambda": home_lam, "away_lambda": away_lam})


@dataclass(frozen=True)
class CountMarketModel:
    model_id: str
    market_family: str
    home_mean: float
    away_mean: float

    def predict(self, lines: tuple[float, ...] = (7.5, 8.5, 9.5)) -> MarketPrediction:
        total = max(0.05, self.home_mean + self.away_mean)
        probs: list[MarketProbability] = []
        for line in lines:
            over = _probability_event(total, line, True)
            probs += [self._result(f"{self.market_family}_ou", f"over_{line}", over), self._result(f"{self.market_family}_ou", f"under_{line}", 1.0 - over)]
        return MarketPrediction(model_id=self.model_id, market_family=self.market_family, probabilities=probs, feature_snapshot={"home_mean": self.home_mean, "away_mean": self.away_mean})

    def _result(self, market: str, selection: str, probability: float) -> MarketProbability:
        p = max(1e-9, min(1.0, probability))
        return MarketProbability(model_id=self.model_id, market=market, selection=selection, probability=p, fair_odds=1.0 / p)


@dataclass(frozen=True)
class CornerMarketModel(CountMarketModel):
    model_id: str = "football.corner_market.v1"
    market_family: str = "corners"
    home_mean: float = 5.0
    away_mean: float = 4.0


@dataclass(frozen=True)
class CardMarketModel(CountMarketModel):
    model_id: str = "football.card_market.v1"
    market_family: str = "cards"
    home_mean: float = 1.8
    away_mean: float = 2.0


@dataclass(frozen=True)
class ShotMarketModel(CountMarketModel):
    model_id: str = "football.shot_market.v1"
    market_family: str = "shots"
    home_mean: float = 5.0
    away_mean: float = 3.8

    def player_probability(self, expected_shots: float, line: float = 0.5) -> MarketProbability:
        p = _probability_event(max(expected_shots, 0.01), line, True)
        return self._result("player_shots_ou", f"over_{line}", p)


@dataclass(frozen=True)
class PlayerGoalModel:
    model_id: str = "football.player_goal.v1"

    def anytime_scorer(self, expected_goals: float) -> MarketProbability:
        p = 1.0 - math.exp(-max(expected_goals, 0.0))
        return MarketProbability(model_id=self.model_id, market="anytime_scorer", selection="yes", probability=p, fair_odds=1.0 / max(p, 1e-9))


@dataclass(frozen=True)
class LiveStateModel:
    model_id: str = "football.live_state.v1"

    def remaining_goal_rate(self, home_lambda: float, away_lambda: float, minute: int, score_total: int = 0) -> float:
        remaining = max(0.0, min(1.0, (90.0 - minute) / 90.0))
        base = max(0.01, home_lambda + away_lambda)
        return base * remaining

    def predict(self, home_lambda: float, away_lambda: float, minute: int, current_total_goals: int = 0, lines: tuple[float, ...] = (0.5, 1.5, 2.5)) -> MarketPrediction:
        remaining_rate = self.remaining_goal_rate(home_lambda, away_lambda, minute, current_total_goals)
        remaining_needed = [line - current_total_goals for line in lines]
        probabilities: list[MarketProbability] = []
        for line, needed in zip(lines, remaining_needed, strict=True):
            if needed <= 0:
                over = 1.0
            else:
                over = _probability_event(remaining_rate, needed - 0.5, True)
            probabilities += [self._result("live_total", f"over_{line}", over), self._result("live_total", f"under_{line}", 1.0 - over)]
        return MarketPrediction(model_id=self.model_id, market_family="live", probabilities=probabilities, feature_snapshot={"minute": float(minute), "remaining_goal_rate": remaining_rate, "current_total_goals": float(current_total_goals)})

    def _result(self, market: str, selection: str, probability: float) -> MarketProbability:
        p = max(1e-9, min(1.0, probability))
        return MarketProbability(model_id=self.model_id, market=market, selection=selection, probability=p, fair_odds=1.0 / p)


@dataclass(frozen=True)
class FootballMarketModelSuite:
    """Explicit registry of market-specific probability engines."""

    goals: GoalMarketModel = GoalMarketModel()
    result: ResultMarketModel = ResultMarketModel()
    corners: CornerMarketModel = CornerMarketModel()
    cards: CardMarketModel = CardMarketModel()
    shots: ShotMarketModel = ShotMarketModel()
    player_goals: PlayerGoalModel = PlayerGoalModel()
    live: LiveStateModel = LiveStateModel()
