;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(244,246,246,1)
fgcolor=rgb(0,86,97)
palette_color_0=rgb(0,59,66)
palette_color_1=rgb(227,78,28)
palette_color_10=rgb(0,209,122)
palette_color_11=rgb(255,140,0)
palette_color_12=rgb(15,163,255)
palette_color_13=rgb(255,107,159)
palette_color_14=rgb(0,203,230)
palette_color_15=rgb(187,195,196)
palette_color_2=rgb(0,179,104)
palette_color_3=rgb(244,151,37)
palette_color_4=rgb(0,148,240)
palette_color_5=rgb(255,87,146)
palette_color_6=rgb(0,189,214)
palette_color_7=rgb(140,166,166)
palette_color_8=rgb(0,77,87)
palette_color_9=rgb(255,64,0)
color_preset=Noctis Hibernus
