;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(48,36,61,1)
fgcolor=rgb(204,191,217)
palette_color_0=rgb(54,47,61)
palette_color_1=rgb(230,101,51)
palette_color_10=rgb(96,235,177)
palette_color_11=rgb(230,149,51)
palette_color_12=rgb(96,182,235)
palette_color_13=rgb(231,152,179)
palette_color_14=rgb(96,219,235)
palette_color_15=rgb(204,191,217)
palette_color_2=rgb(73,233,166)
palette_color_3=rgb(228,183,129)
palette_color_4=rgb(73,172,233)
palette_color_5=rgb(223,118,155)
palette_color_6=rgb(73,214,233)
palette_color_7=rgb(191,175,207)
palette_color_8=rgb(89,78,101)
palette_color_9=rgb(233,119,73)
color_preset=Noctis Viola
