[colors]
background = '#322a2d'
foreground = '#cbbec2'
selection-background = '#4a3339'
selection-foreground = '#cbbec2'
cursor = '#cbbec2'
black = '#47393e'
red = '#e66533'
green = '#49e9a6'
yellow = '#e4b781'
blue = '#49ace9'
magenta = '#df769b'
cyan = '#49d6e9'
white = '#b9acb0'
light_black = '#69545b'
light_red = '#e97749'
light_green = '#60ebb1'
light_yellow = '#e69533'
light_blue = '#60b6eb'
light_magenta = '#e798b3'
light_cyan = '#60dbeb'
light_white = '#cbbec2'
