[colors]
background = '#031417'
foreground = '#b2cacd'
selection-background = '#0d2a2f'
selection-foreground = '#b2cacd'
cursor = '#b2cacd'
black = '#324a4d'
red = '#e66533'
green = '#49e9a6'
yellow = '#e4b781'
blue = '#49ace9'
magenta = '#df769b'
cyan = '#49d6e9'
white = '#b2cacd'
light_black = '#47686c'
light_red = '#e97749'
light_green = '#60ebb1'
light_yellow = '#e69533'
light_blue = '#60b6eb'
light_magenta = '#e798b3'
light_cyan = '#60dbeb'
light_white = '#c1d4d7'
