[colors]
background = '#1b2932'
foreground = '#c5cdd3'
selection-background = '#263c4a'
selection-foreground = '#c5cdd3'
cursor = '#c5cdd3'
black = '#182a35'
red = '#c08872'
green = '#72c09f'
yellow = '#c8a984'
blue = '#6196b8'
magenta = '#c28097'
cyan = '#72b7c0'
white = '#c5cdd3'
light_black = '#425866'
light_red = '#ca8468'
light_green = '#84c8ab'
light_yellow = '#d1aa7b'
light_blue = '#68a4ca'
light_magenta = '#c88da2'
light_cyan = '#84c0c8'
light_white = '#c5d1d3'
