[colors]
background = '#f2f1f8'
foreground = '#0c006b'
selection-background = '#d5d3e5'
selection-foreground = '#0c006b'
cursor = '#0c006b'
black = '#0c006b'
red = '#e34e1c'
green = '#00b368'
yellow = '#f49725'
blue = '#0094f0'
magenta = '#ff5792'
cyan = '#00bdd6'
white = '#8ca6a6'
light_black = '#0f0080'
light_red = '#ff4000'
light_green = '#00d17a'
light_yellow = '#ff8c00'
light_blue = '#0fa3ff'
light_magenta = '#ff6b9f'
light_cyan = '#00cbe6'
light_white = '#bbc3c4'
